#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# A script that displays information about subdomains.

domain_info() {
    local domain=$1
    local subdomain=$2
    local line
    line=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$subdomain $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
  subdomains=("www" "lb-01" "web-01" "web-02")
  for subdomain in "${subdomains[@]}"; do
    domain_info "$1" "$subdomain"
  done
elif [ "$#" == 2 ]; then
  domain_info "$1" "$2"
fi

