#!/usr/bin/env bash
# A script that installs nginx on my web-01 server:
# Nginx should be listening on port 80.
# It should return a page that contains the string "Hello World!" at the root
# with a curl GET request.

apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /usr/share/nginx/html/index.html
service nginx start
service nginx restart
