#!/usr/bin/env bash
# A script that installs nginx on my web-01 server:
# Nginx should be listening on port 80.
# It should return a page that contains the string "Hello World!" at the root
# with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /var/www/html
sudo echo "Hello World!" > /var/www/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
