#!/usr/bin/env bash
# A script that configures my Nginx server so that /redirect_me is redirecting
# to another page.
# The redirection must be a "301 Moved Permanently"

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
cm="rewrite ^/redirect_me https://www.youtube.com/ permanent;"
sudo sed -i "66i $cm" /etc/nginx/sites-available/default

sudo service nginx start
