#!/usr/bin/env bash
# A script that configures my Nginx server so that /redirect_me is redirecting
# to another page.
# The redirection must be a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx

mkdir /var/www/html
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
    location /redirect_me {
        return 301 http://google.com/;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
