#!/usr/bin/env bash
# Script to install and configure the latest version of HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

# Update package lists
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy
apt-get update
apt-get install -y haproxy

# Enable HAProxy via init script
echo "ENABLED=1" >> /etc/default/haproxy

# Backup and create a new HAProxy configuration
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

# Configure HAProxy with roundrobin algorithm
cat <<EOF >> /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen Augustie.tech 
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 271026-web-01 100.26.50.102:80 check
    server 271026-web-02 54.162.241.88:80 check
EOF

# Restart HAProxy to apply changes
/etc/init.d/haproxy restart

# Ensure HAProxy starts on boot
update-rc.d haproxy defaults
