#!/usr/bin/env bash
# A script that shows the minimum number of commands to make nginx listen on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
