#!/usr/bin/env bash
# A script that does the following:
#   Create a file /var/run/myscript.pid containing it's PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM signal
#   Displays "Y U no love me?!" upon receiving a SIGINT signal
#   Deletes the file /var/run/myscript.pid and terminates itself when
#   receiving a SIGQUIT or SIGTERM signal.

terminate()
{
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminate' SIGTERM
  trap 'terminate' SIGQUIT
done
