#!/usr/bin/env bash
# A script that displays the contents of the file `/etc/passwd`.
# Script only displays the username, user id, and home directory path foor the user.

while read passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
