#!/usr/bin/env bash
# A script that displays the contents of the current directory in list format.
# where only the part of the name after the first dash is displayed. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
