#!/usr/bin/env bash
# A script that fixes a container so Nginx run as the nginx user
# nginx must be listening on all active IPs on port 8080.

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root."
    exit 1
fi

# Update Nginx configuration
sed -i -e 's/#user www-data/user nginx/' -e 's/80/8080/g' /etc/nginx/nginx.conf /etc/nginx/sites-available/default

# Restart Nginx using systemctl
systemctl restart nginx
